# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-No_To_Garbage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-No_To_Garbage
  pod 'Firebase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
end

target 'WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WidgetExtension

end
