# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'iOS-No_To_Garbage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-No_To_Garbage
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	#pod 'SunburstDiagram', '~> 1.1'
end
